### ISSUE TITLE
Where to put boilerplates

### ISSUE THREAD

**Issue by simonfranzen** [gramantin/awesome-rails#71]
Hey, I have created a boilerplate for rails6 + graphql https://github.com/zauberware/rails-devise-graphql
Where can I include this here in the Readme?

**Comment by ekremkaraca** [comment]
Hi @simonfranzen, I was considering to have starters listed since there are some noteworthy examples like yours. You can add a section called "starters/boilerplates" before "other rails tools" and add yours by sending a pull request.

**Comment by simonfranzen** [comment]
PR is open https://github.com/gramantin/awesome-rails/pulls

**Comment by ekremkaraca** [comment]
@simonfranzen merged, thanks so much!
